### PR TITLE
Google Chrome flash detection 

### PR DESCRIPTION
**Pull request by zfz**
Hi, I've add a function to detect flash playing in Google Chrome. Thanks.

### CODE REVIEW

**Comment by iye** [comment]
I don't have Ubuntu nor Chrome and I'm not willing to install them to try this, but I think it would be better solution to replace the following line in lightsOn.sh in master:

```
flash_process=`pgrep -lfc "chromium-browser --type=plugin --plugin-path=/usr/lib/adobe-flashplugin"`
```

with:

edit:
    #DO NOT USE
    flash_process=`pgrep -lfc "._((c|C)hrome|chromium)._flashp.*"' 

```
#USE THIS!
flash_process=`pgrep -lfc ".*((c|C)hrome|chromium).*flashp.*"`
```

Notice I'm matching Chrome and chrome (notice caps), as I know for sure it comes in both ways for Chrome at least. Also this would match libflashplugin.so and peppersomethingflashplayer.lib.
Activating Chromium detection will match chrome and chromium.

Would you mind pasting here the complete process name of Chrome with and without pepperflashsomething so I can see if this would work? Do you know if Chrome process always has as a parameter the path to it's flash player lib?

**Comment by zfz** [comment]
Yeah @iye , your thought to have both Chrome and Chromium detected is elegant. 

The command 'flash_process=pgrep -lfc ***' could not detect flash process '/opt/google/chrome/PepperFlash/libpepflashplayer.so'. So I disabled it.

The complete process with Chrome now is '/usr/lib/flashplugin-installer/libflashplayer.so'. Here is the screen shot of my flash configuration in Chrome: http://i.stack.imgur.com/0Hewb.png . And my google Chrome version: 21.0.1180.81.
Thanks.

**Comment by iye** [comment]
Would you mind pasting here the output of "ps aux | grep flash"? This while having Chrome playing a flash video.

**Comment by zfz** [comment]
Okay, this is the output of 'ps aux | grep flash':
zfz      20966 26.8  5.2 915944 206540 ?       Rl   22:03  11:32 /opt/google/chrome/chrome --type=plugin --plugin-path=/usr/lib/flashplugin-installer/libflashplayer.so --lang=en-US --channel=20770.19.396856114
zfz      22103  0.0  0.0  13624   932 pts/1    S+   22:46   0:00 grep --color=auto flash

**Comment by iye** [comment]
Try this line again, it's different than the one I wrote above.

```
flash_process=`pgrep -lfc ".*((c|C)hrome|chromium).*flashp.*"`
```

**Comment by zfz** [comment]
The command 'pgrep -lfc "._((c|C)hrome|chromium)._flashp.*"' can get 1. It works for me!

**Comment by iye** [comment]
Chrome detection added to master.

**Pull request closed without merging**
